Models/Day.cs
namespace Project.Models
{
    public class Day
    {
        //[Key]
        public int DayId { get; set; } // Primary Key
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int WaitingPeriod { get; set; }
        public DateTime AppointmentTime { get; set; }
        public string DayName { get; set; }

        // Foreign Key to Doc

        public Doctor Doc { get; set; }

        // Navigation Properties
        public  ICollection<Booking> Bookings { get; set; }
        public ICollection<BlockOutHours> BlockOutHours { get; set; }

    }
}

ViewModels/DayViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Project.ViewModels
{
    public class DayViewModel
    {
        public List<DayDto> Days { get; set; }
    }

    public class DayDto
    {
        public string DayName { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int WaitingPeriod { get; set; }

        public DateTime AppointmentTime { get; set; }

        // BlockOutHours for each day
        public List<BlockOutHourDto> BlockOutHours { get; set; }
    }

    public class BlockOutHourDto
    {
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
    }


}

Controllers/DayController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Project.Models;
using Project.Services;
using Project.ViewModels;

namespace Project.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class DayController : Controller
    {
        private readonly VeseetaDBContext context;
        private readonly UserManager<User> _userManager;

        IDayRepository dayRepository;
        public DayController(VeseetaDBContext context, UserManager<User> userManager, IDayRepository dayRepository)
        {
            this.context = context;
            this._userManager = userManager;
            this.dayRepository = dayRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var docId = _userManager.GetUserId(User);
            Console.WriteLine(docId);

            if (docId == null)
                return View("404");
            var doctor = context.Doctors.FirstOrDefault(d => d.UserId == docId);
            Console.WriteLine(doctor);
            var Days = context.Days
            .Where(day => day.Doc == doctor).ToList();
            //Console.WriteLine(Days[0]?.Doc.DoctorId);
            ViewBag.message = TempData["Message"];

            if (Days != null)
                return View(Days);
            return View(Days);
        }

        [HttpGet]
        public ActionResult Create() {
            var docId = _userManager.GetUserId(User);
            var doctor = context.Doctors.FirstOrDefault(d => d.UserId == docId);
            var Days = context.Days
            .Where(day => day.Doc == doctor).ToList();

            var allDaysOfWeek = new List<string> { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };

            // Filter out the selected days
            if (Days != null && Days.Any())
            {
                allDaysOfWeek = allDaysOfWeek.Except(Days.Select(d => d.DayName)).ToList();
            }

            var Dayview = new DayViewModel();
            var tuble = Tuple.Create(Dayview, allDaysOfWeek);
            return View(tuble);
        }

        [HttpPost]
        public async Task<IActionResult> Add(DayViewModel d)
        {
            if (ModelState.IsValid)
            {
                var docId = _userManager.GetUserId(User);
           
                var doctor = context.Doctors.FirstOrDefault(d => d.UserId == docId);
               
                foreach (var day in d.Days)
                {
                    var newDay = new Day
                    {
                        DayName = day.DayName,
                        StartTime = day.StartTime,
                        EndTime = day.EndTime,
                        WaitingPeriod = day.WaitingPeriod,
                        AppointmentTime = day.AppointmentTime,
                        Doc = doctor,
                    };

                    //context.Days.Add(newDay);
                    //context.SaveChanges();
                    dayRepository.AddDay(newDay);

                    foreach (var blockhours in day.BlockOutHours)
                    {
                        var newblockhour = new BlockOutHours
                        {
                            StartTime = blockhours.StartTime,
                            EndTime = blockhours.EndTime,
                            Day = newDay,
                        };
                        context.BlockOutHours.Add(newblockhour);
                        context.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            return View("Index");
        }


        public IActionResult Delete(int DayId) {

            var day = context.Days
                .Include(day => day.BlockOutHours)
                .Include(day => day.Bookings)
                .FirstOrDefault(day => day.DayId == DayId);

            if (day != null) {
                

                if (day.BlockOutHours.Any() && day.BlockOutHours != null) {
                    context.BlockOutHours.RemoveRange(day.BlockOutHours);
                }
                if(day.Bookings.Any() && day.Bookings != null) {
                    context.Bookings.RemoveRange(day.Bookings);
                }
                
                context.Days.Remove(day);

                context.SaveChanges();
                TempData["Message"] = "Day Deleted Succesffully";
                return RedirectToAction("Index");

            }


            return RedirectToAction("Index");

        }

        public IActionResult Details(int DayId) {

            var day = context.Days
                .Include(day => day.BlockOutHours)
                .SingleOrDefault(day => day.DayId == DayId);

            if (day != null) { 
            
                var blockOutHours = day.BlockOutHours.ToList();
                ViewBag.BHMessage = TempData["BHMessage"];
                return View(blockOutHours);
            }

            return RedirectToAction("Index");
        
        }


    }
}

Views/Day/Create.cshtml
@model Tuple<DayViewModel,List<String>>
@{
    ViewData["Title"] = "Add Day";
}

<form asp-action="Add" method="post" class="d-flex justify-content-center align-items-center flex-column">
    <div id="days-container" class="w-50">
        <div class="day-item">
            <h4>Day Details</h4>
            <div class="form-group">
                <label class="form-label">Day Name</label>
                <select name="Days[0].DayName" class="form-control day-select" required>
                    <option value="">Select Day</option>
                    @foreach(var day in Model.Item2)
                    {
                        <option value="@day">@day</option>

                    }
                </select>
            </div>
            <div class="form-group">
                <label class="form-label">Start Time</label>
                <input type="time" name="Days[0].StartTime" required class="form-control" />
            </div>
            <div class="form-group">
                <label class="form-label">End Time</label>
                <input type="time" name="Days[0].EndTime" required class="form-control" />
            </div>
            <div class="form-group">
                <label class="form-label">Appointment Time</label>
                <input type="time" name="Days[0].AppointmentTime" required class="form-control" />
            </div>
            <div class="form-group">
                <label class="form-label">Waiting Period</label>
                <input type="text" name="Days[0].WaitingPeriod" placeholder="Waiting Period" required class="form-control" />
            </div>

            <div class="blockout-hours">
                <h5>BlockOut Hours</h5>
                <div class="form-group">
                    <label class="form-label">Start Hour</label>
                    <input type="time" name="Days[0].BlockOutHours[0].StartTime" placeholder="Start Time" required class="form-control" />
                </div>
                <div class="form-group">
                    <label class="form-label">End Hour</label>
                    <input type="time" name="Days[0].BlockOutHours[0].EndTime" placeholder="End Time" required class="form-control" />
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3 mb-3">
        @* <button type="button" onclick="addDay()" id="daybtn" class="btn btn-primary">Add More Day</button> *@
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>

<script>
    // List of days of the week
    var daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

    function addDay() {
        var dayCount = document.querySelectorAll('.day-item').length;
        var container = document.getElementById('days-container');
        var dayButton = document.getElementById("daybtn");
        if (dayCount < 7) {
            var availableDays = daysOfWeek.map(function (day) {
                return `<option value="${day}">${day}</option>`;
            }).join('');

            var dayTemplate = `
                    <div class="day-item">
                        <h4>Day Details</h4>
                        <div class="form-group">
                            <label class="form-label">Day Name</label>
                            <select name="Days[${dayCount}].DayName" class="form-control day-select" required>
                                <option value="">Select Day</option>
                                ${availableDays}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Start Time</label>
                            <input type="time" name="Days[${dayCount}].StartTime" required class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label class="form-label">End Time</label>
                            <input type="time" name="Days[${dayCount}].EndTime" required class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="form-label">Appointment Time</label>
                            <input type="time" name="Days[${dayCount}].AppointmentTime" required class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="form-label">Waiting Period</label>
                            <input type="text" name="Days[${dayCount}].WaitingPeriod" placeholder="Waiting Period" required class="form-control" />
                        </div>

                        <div class="blockout-hours">
                            <h5>BlockOut Hours</h5>
                            <div class="form-group">
                                <label class="form-label">Start Hour</label>
                                <input type="time" name="Days[${dayCount}].BlockOutHours[0].StartTime" placeholder="Start Time" required class="form-control" />
                            </div>
                            <div class="form-group">
                                <label class="form-label">End Hour</label>
                                <input type="time" name="Days[${dayCount}].BlockOutHours[0].EndTime" placeholder="End Time" required class="form-control" />
                            </div>
                        </div>
                    </div>
                `;

            container.insertAdjacentHTML('beforeend', dayTemplate);

            // Remove the selected day from the options
            var daySelect = document.querySelector(`select[name="Days[${dayCount}].DayName"]`);
            daySelect.addEventListener('change', function () {
                var selectedDay = this.value;
                daysOfWeek = daysOfWeek.filter(function (day) {
                    return day !== selectedDay;
                });
                // Disable the button when all days are added
                if (dayCount >= 6) {
                    dayButton.disabled = true;
                }
            });
        }
    }
</script>

Views/Day/Details.cshtml
@model List<BlockOutHours>

@{
    ViewData["Title"] = "Day Details";
}

@if (ViewBag?.BHMessage != null)
{
<div class="alert alert-success">
    @ViewBag.BHMessage
</div>
}


@if (!Model.Any())
{
    <div class="d-flex align-content-center justify-content-center mt-3 flex-column flex-wrap">
        <h1>No data Found</h1>
        <a href="/Day/Create" class="btn btn-primary mb-2 d-block">Add New Day</a>
    </div>
}
else
{
    
    <div class="d-flex align-content-center justify-content-center mt-3">
        <div class="table-responsive w-75">
            <table class="table table-hover table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        
                        <th scope="col">Start Hour</th>
                        <th scope="col">End Hour</th>
                       
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var hour in Model)
                    {
                        <tr>
                            
                            <td>@hour.StartTime</td>
                            <td>@hour.EndTime</td>
                         
                            <td>
                                <a href="@Url.Action("Delete", "BlockOutHours", new { HourId = hour.BlockOutHoursId ,DayId = hour.Day.DayId})" class="btn btn-danger">Delete</a>
                                <a href="@Url.Action("Details", "Day", new { HourId = hour.BlockOutHoursId})" class="btn btn-primary ms-2">Details</a>
                            </td>

                            @* <td>@day.AppointmentTime</td> *@
                        </tr>
                    }

                </tbody>
            </table>
            <a href="/Day/Create" class="btn btn-primary mb-2">Add New Day</a>
        </div>
    </div>
}

Views/Day/Index.cshtml
@model List<Day>
@{
    ViewData["Title"] = "Days";
}

@if (ViewBag?.message != null)
    {
        <div class="alert alert-success">
            @ViewBag.Message
        </div>
    }
<style>
    .disabled {
        pointer-events: none;
        color: gray; 
        text-decoration: none; 
    }
</style>


@if (!Model.Any())
{
    <div class="d-flex align-content-center justify-content-center mt-3 flex-column flex-wrap">
        <h1>No data Found</h1>
        <a href="/Day/Create" class="btn btn-primary mb-2 d-block">Add New Day</a>
    </div>
}
else
{
   
    <div class="d-flex align-content-center justify-content-center mt-3">
        <div class="table-responsive w-75">
            <table class="table table-hover table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">DayName</th>
                        <th scope="col">Start Hour</th>
                        <th scope="col">End Hour</th>
                        <th scope="col">Waiting Period</th>
                        @* <th scope="col">Appointment Time</th>  *@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var day in Model)
                    {
                        <tr>
                            <td>@day.DayName</td>
                            <td>@day.StartTime</td>
                            <td>@day.EndTime</td>
                            <td>@day.WaitingPeriod</td>
                            @* <td>@day.AppointmentTime</td> *@
                            <td>
                                <a href="@Url.Action("Delete", "Day", new { DayId = day.DayId })" class="btn btn-danger">Delete</a>
                                <a href="@Url.Action("Details", "Day", new { DayId = day.DayId })" class="btn btn-primary ms-2">Details</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <a href="/Day/Create" class="btn btn-primary mb-2" id="addbtn">Add New Day</a>
        </div>
    </div>
 }

 <script>
    document.addEventListener("DOMContentLoaded", function () {
        var btn = document.getElementById("addbtn");
        console.log(btn);
        var daycount = @Model.Count;
        console.log(daycount);
        if (daycount === 7) {
            btn.classList.add("disabled")
        } 
   
    })
</script>
   
      